photo_webs/imageposts/urls.py
from django.urls import path

from . import views

app_name = "imageposts"

urlpatterns = [
    path("post/", views.add_post, name="add-post"),
    path("post/<int:pk>/", views.ImageDetailView.as_view(), name="show"),
    path("post/<int:pk>/edit/", views.edit_post, name="edit"),
]

photo_webs/photo_webs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', include('web.urls')),
    path("user/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls")),
    path("imageposts/", include("imageposts.urls")),
    path("", include("web.urls")),
    # path('', ImagepostListView.as_view(), name='all-imgposts'),
    # path('', include('images.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo_webs/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("", views.profile, name="profile"),
    path("settings/", views.user_edit, name="user-settings"),
    path("profile/settings/", views.profile_edit, name="profile-settings"),
    path("instagram/", views.add_insta_profile, name="profile-insta"),
    path("instagram/<int:pk>/", views.show_insta_profile, name="profile-insta-show"),
    path("settings/password/", views.change_password, name="change_password"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="profile"),
    path("<int:pk>/images/", views.UserImagesView.as_view(), name="profile-images"),
    path("<int:pk>/bio/", views.UserBioView.as_view(), name="profile-bio"),
    path("<int:pk>/followers/", views.FollowerView.as_view(), name="profile-follows"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

photo_webs/web/urls.py
from django.urls import path
from imageposts.views import ImagepostListView

from . import views

app_name = "web"

urlpatterns = [
    path("", ImagepostListView.as_view(), name="all-imgposts"),
    path("license/", views.license, name="license"),
    path("license/de/", views.license_de, name="license_de"),
    path("imprint/", views.imprint, name="imprint"),
    path("imprint/de/", views.imprint_de, name="imprint_de"),
    path("license/de", views.license_de, name="license_de"),
    path("search/<str:pk>", views.search, name="search"),
]

photo_webs/web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static "/css/style.css" %}">
    <link rel="stylesheet" href="{% static "/fonts/css/line-awesome.min.css" %}">
    <script src="{% static "/js/btt.js"%}"></script>
    <script src="{% static "/js/search.js" %}"></script>
    {% endblock head %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <title>PhotoHub - {% block title %} Home {% endblock title %}</title>
</head>

<body class="bg-dark" name="top">
    <header>

        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <!-- logo and name -->
            <a class="navbar-brand" href="/">
                {% load static %}
                <img src="{% static "icons/logo_photohub_red.png" %}" width="30" height="30"
                    class="d-inline-block align-top" alt="">
                PhotoHub
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'web:license' %}">The PhotoHub license</a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item">
                            <a class="nav-link text-warning" href="/admin">/admin</a>
                    </li>
                    {% endif %}
                </ul>

                <!-- user dropdown or login buttons-->
                {% if user.is_authenticated %}
                <div class="btn-group mr-2">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </button>
                    <div class="dropdown-menu"">
                              <a href="{% url 'user:profile' %}{{ user.id }}" class="dropdown-item"><i class="las la-user"></i> My profile</a>
                              <a href="{% url 'user:user-settings' %}" class="dropdown-item"><i class="las la-cog"></i> Settings</a>
                              <a href="{% url 'user:profile-insta' %}" class="dropdown-item"><i class="lab la-instagram"></i> Import from Instagram</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'logout' %}" class="dropdown-item"><i class="las la-sign-out-alt"></i> Not {{ user.username }}? Log out</a>
                    </div>
                </div>
                {% else %}
                <a class="btn btn-outline-primary mr-2" href="{% url 'login' %}" role="button">Log in</a>
                <a class="btn btn-primary mr-2" href="{% url 'user:signup' %}" role="button">Sign up</a>
                {% endif %}
                <form class="form-inline my-2 my-lg-0" onsubmit="return search();">
                    <input id="search_text" class="form-control mr-sm-2" placeholder="Discover PhotoHub"
                        aria-label="Search">
                    <p id="search_button" class="btn btn-outline-primary my-2 my-sm-0" onclick="search()">Search</p>
                </form>
            </div>
        </nav>
    </header>

    {% block intro %} {% endblock intro %}
    {% block content %} {% endblock content %}
    {% block floating_nav %}
    {% block button_top %}<a id="back-top-btn-round" class="btn btn-primary floating_button2" onclick="topFunction()" href="#top"><i id="back-top-btn" class="las la-arrow-circle-up"></i></a>{% endblock button_top %}
    {% block button_upload %}{% if user.is_authenticated %}<a id="upload-btn-sm" class="btn btn-primary floating_button" href="{% url 'imageposts:add-post' %}" role="button"><i id="upload-btn" class="las la-camera-retro"></i></a>{% endif %}{% endblock button_upload %}
    {% endblock floating_nav %}
    
    <footer>
        <a href="/" class="text-light">© 2019-2020 PhotoHub</a>
        <a href="{% url 'web:imprint' %}#imprint"class="text-light">Imprint</a>
        <a href="{% url 'web:imprint' %}#terms"class="text-light">Terms</a>
    </footer>

</body>

</html>

photo_webs/web/templates/web/home.html
{% extends "web/base.html" %}

{% block intro %}
{% load static %}
<link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
{% load app_filters %}

<div class="card text-center mt-5 bg-dark" style="border-radius: 0;">
  <div class="card-body pt-5 pb-5" style="background-image: url({% static "media/default_page_banner.jpeg" %}); background-size: cover; 
    background-repeat: no-repeat;
    background-position: center center;">
    <br>
    <h4 class="card-title text-danger"><strong>Awesome & free pictures</strong></h4>
    <h5 class="card-text text-light"><strong>Free pictures from our talented community combined with a simple
        license</strong></h5>
    <br>
    <a href="{% url 'web:search' pk='wallpaper'|title %}" class="btn btn-primary">Wallpapers</a><a
      href="{% url 'web:search' pk='nature'|title %}" class="btn btn-primary ml-2 mr-2">Nature</a><a
      href="{% url 'web:search' pk='travel'|title %}" class="btn btn-primary">Travel</a>
    <br><br>
  </div>
  <div class="card-footer text-dark bg-primary">
    {% if user.is_authenticated %}
    Hello {{ user.username }}. Add new pictures to your <a href="{% url 'user:profile' %}{{ user.id }}"
      class="text-light">profile</a>.
    {% else %}
    Discover the latest pictures.
    {% endif %}
  </div>
</div>
{% endblock intro %}

{% block content %}
<div class="gallery-big">
  {% for image in page_obj %}
  {% if image.img.url != "/uploaded_content/media/773433.jpg" and image.img_thumbnail.url != "/uploaded_content/media/773433.jpg"%}

  {% include 'imageposts/snippet/img_card.html' with image=image user=user %}
  {% endif %}
  {% endfor %}
</div>
 <!-- paginator -->
 <nav aria-label="pagination">
  <ul class="pagination justify-content-center pagination-lg">
    {% for count in page_obj.paginator.num_pages|int_to_list_string %}
      {% if count == '1' %}
      <li id="page-item" class="page-item"><a href="?page={{count}}" class="page-link text-primary">first</a></li>
      {% elif count == page_obj.paginator.num_pages|to_string %}
      <li id="page-item" class="page-item"><a href="?page={{count}}" class="page-link text-primary">last</a></li>
      {% elif count == page_obj.previous_page_number|to_string %}
      <li id="page-item" class="page-item"><a href="?page={{count}}" class="page-link text-primary">previous</a></li>
      {% elif count == page_obj.next_page_number|to_string %}
      <li id="page-item" class="page-item"><a href="?page={{count}}" class="page-link text-primary">next</a></li>
      {% elif count == page_obj.number|to_string %}
      <li id="page-item" class="page-item b"><a href="?page={{count}}" class="page-link text-primary"><strong>{{ count }}</strong></a></li>
      {% else %}
      <li id="page-item" class="page-item"><a href="?page={{count}}" class="page-link text-primary">{{ count }}</a></li>
      {% endif %}
      {% endfor %}
  </ul>
</nav>
<!-- /paginator -->
{% endblock content %}

photo_webs/web/templates/web/license.html
{% extends "web/base.html" %}

{% block intro %}
{% load static %}

<div class="card text-center mt-5 bg-dark" style="border-radius: 0;">
    <div class="card-body pt-5 pb-5" style="background-image: url({% static "media/default_page_banner.jpeg" %}); background-size: cover; 
    background-repeat: no-repeat;
    background-position: center center;">
        <br>
        <h1 class="text-light">PhotoHub License</h1>
        <h2><a></a></h2>
    </div>
    <div class="card-footer text-dark bg-primary">
        {% if user.is_authenticated %}
        Hello {{ user.username }}. Add new pictures to your <a href="{% url 'user:profile' %}{{ user.id }}"
            class="text-light">profile</a>.
        {% else %}
        Discover the latest pictures.
        {% endif %}
    </div>
</div>

{% endblock intro %}

{% block content %}

<article class="p-4">
    <a href="{% url 'web:license_de' %}" class="text-light btn btn-primary">deutsch</a>
    <h1 class="text-light mt-3">Simplified PhotoHub license</h1>
    <p class="text-light">
        Our license offers our users extensive freedom for commercial, private or educational purposes, as well as legal security, while protecting our authors and the community from misuse of their works.
        <br><br>
        We provide a simplified summary here so that every user understands which points need to be considered with our license. However, it is not a legally binding document.
    </p>
    <h3 class="text-light mt-5">What is allowed? (Image users and image authors)</h3>
    <ul mb-4 class="text-light list-group mt-4">
        <li class="list-group-item bg-dark border-success">&#x2714 You can use all PhotoHub content for free for commercial and non-commercial projects, both for
            digital as well as printed products. Restrictions are in the "What is not allowed?"</li>
        <li class="list-group-item bg-dark border-success">&#x2714 You don't need to get permission to use the images. Neither from PhotoHub, nor from the picture author.</li>
        <li class="list-group-item bg-dark border-success">&#x2714 It is not necessary to mention PhotoHub, but we are happy to receive a voluntary mention. A link is necessary for commercial use.</li>
        <li class="list-group-item bg-dark border-success"> &#x2714 You can change all PhotoHub content.</li>
    </ul>
    <h3 class="text-light mt-4">What is not allowed? (Image users)</h3>
    <ul class="text-light list-group mt-4">
        <li class="list-group-item bg-dark border-danger">&#10007 Do not sell unchanged copies of the works. Neither as digital nor physical products.</li>
        <li class="list-group-item bg-dark border-danger">&#10007 Recognizable people cannot be represented in a political context or in an offensive manner. </li>
        <li class="list-group-item bg-dark border-danger">&#10007 Do not suggest that recognizable persons, the picture author, PhotoHub or recognizable brands on the pictures recommend your product, support or advocate your views, or are connected with you or your product / opinion / grouping / company</li>
    </ul>
    <br>
    <section class="card border-info bg-dark p-4 mt-4">
        <h2 class="text-light">License text</h2>
        <p class="text-light">
            PhotoHub license - use of images
            <br><br>
            Images on PhotoHub are provided under the PhotoHub license under the following conditions.
            <br>
            The PhotoHub license gives you an irrevocable, worldwide, non-exclusive and royalty-free right to use, download, copy and modify the images for commercial and non-commercial purposes. It is not necessary to name the photo author or PhotoHub, but we would be happy to provide a voluntary source.
            <br><br>
            The PhotoHub license does not allow:
            <br><br>
            - the sale or distribution of images in digital and physical form, in particular as stock photos or digital wallpapers;
            <br><br>
            - the sale or distribution of images e.g. as posters, digital prints or physical products, without adding additional elements or otherwise creating added value;
            <br><br>
            - depicting identifiable people in an offensive, pornographic, obscene, immoral, defamatory or political manner;
            <br><br>
            - or the suggestion that depicted people, brands, organizations, etc. endorse certain products or services unless authorized to do so.
            <br><br>
            Please note that although all content on PhotoHub is freely usable for commercial and non-commercial purposes, elements shown in the images, such as identifiable people, logos and brands, may be subject to additional copyrights, property rights, personal rights, trademark rights, etc. Third party approval or licensing of these rights may be required, particularly for commercial applications. PhotoHub does not guarantee that such consent or licenses have been obtained and expressly disclaims any liability in this regard.
        </p>
    </section>
</article>
{% endblock content %}

photo_webs/web/templates/web/license_de.html
{% extends "web/base.html" %}

{% block intro %}
{% load static %}

<div class="card text-center mt-5 bg-dark" style="border-radius: 0;">
    <div class="card-body pt-5 pb-5" style="background-image: url({% static "media/default_page_banner.jpeg" %}); background-size: cover; 
    background-repeat: no-repeat;
    background-position: center center;">
        <br>
        <h1 class="text-light">PhotoHub License</h1>
    </div>
    <div class="card-footer text-dark bg-primary">
        {% if user.is_authenticated %}
        Hello {{ user.username }}. Add new pictures to your <a href="{% url 'user:profile' %}{{ user.id }}"
            class="text-light">profile</a>.
        {% else %}
        Discover the latest pictures.
        {% endif %}
    </div>
</div>
{% endblock intro %}

{% block content %}
<article class="p-4">
    <a href="{% url 'web:license' %}" class="text-light btn btn-primary">english</a>
    <h1 class="text-light mt-3">Vereinfachte PhotoHub Lizenz</h1>
    <p class="text-light">
        Unsere Lizenz bietet unseren Nutzern umfassende Freiheiten für kommerzielle, private oder Bildungszwecke, sowie rechtliche Sicherheit und schützt gleichzeitig unsere Authoren und Community vor Missbrauch ihrer Werke.
        <br><br>
        Damit jeder Nutzer versteht, welche Punkte es bei unserer Lizenz zu beachten gilt, stellen wir hier eine vereinfachte
        Zusammenfassung zur Verfügung. Es handelt sich jedoch nicht um ein rechtlich bindendes Dokument.
    </p>
    <h3 class="text-light mt-5">Was ist erlaubt? (Bildnutzer und Bildauthoren)</h3>
    <ul mb-4 class="text-light list-group mt-4">
        <li class="list-group-item bg-dark border-success">&#x2714 Du darfst alle PhotoHub-Inhalte kostenlos für kommerzielle
            und nicht-kommerzielle Anwendungen nutzen, sowohl für
            digitale als auch gedruckte Produkte. Einschränkungen stehen im Bereich "Was ist nicht gestattet?".</li>
        <li class="list-group-item bg-dark border-success">&#x2714 Du musst keine Genehmigung zur Nutzen der Bilder einholen.
            Weder bei PhotoHub, noch beim Bildauthor.</li>
        <li class="list-group-item bg-dark border-success">&#x2714 Eine Nennung von PhotoHub ist nicht nötig, wobei wir uns über
            eine freiwillige erwähnung freuen. Eine Verlinkung
            ist für kommerzielle Nutzungen nötig. </li>
        <li class="list-group-item bg-dark border-success"> &#x2714 Du darfst alle PhotoHub-Inhalte verändern. </li>
    </ul>
    <h3 class="text-light mt-4">Was ist nicht erlaubt? (Bildnutzer)</h3>
    <ul class="text-light list-group mt-4">
        <li class="list-group-item bg-dark border-danger">&#10007 Verkaufe keine unveränderten Kopien der Werke. Weder als
            digitale noch physische Produkte.</li>
        <li class="list-group-item bg-dark border-danger">&#10007 Erkennbare Personen dürfen nicht im politischen Kontext oder
            auf anstößige Weise dargestellt werden. </li>
        <li class="list-group-item bg-dark border-danger">&#10007 Suggeriere nicht, dass erkennbare Personen, der Bildauthor,
            PhotoHub oder erkennbare Marken auf den Bildern dein
            Produkt empfehlen, oder deine Ansichten unterstützen oder beführworten, bzw. mit dir oder deinem
            Produkt/Meinung/Gruppierung/Unternehmen in Verbindung stehen</li>
    </ul>
    <br>
    <section class="card border-info bg-dark p-4 mt-4">
        <h2 class="text-light">Lizenztext</h2>
        <p class="text-light">
            PhotoHub Lizenz – Nutzung von Bildern
            <br><br>
            Bilder auf PhotoHub werden unter der PhotoHub Lizenz mit den folgenden Bedingungen zur Verfügung gestellt.
            <br>
            Durch die PhotoHub Lizenz erhältst Du ein unwiderrufliches, weltweites, nicht exklusives und gebührenfreies
            Recht,
            die Bilder für kommerzielle und nicht kommerzielle Zwecke zu verwenden, herunterzuladen, zu kopieren und zu
            verändern. Eine Nennung des Bildautors bzw. von PhotoHub ist nicht erforderlich, wir würden uns jedoch über
            eine
            freiwillige Quellenangabe freuen.
            <br><br>
            Die PhotoHub-Lizenz gestattet nicht:
            <br><br>
            - den Verkauf oder Vertrieb von Bildern in digitaler und physischer Form, insbesondere als Stockfotos oder
            digitale
            Wallpaper;
            <br><br>
            - den Verkauf oder Vertrieb von Bildern z.B. als Poster, Digitaldrucke oder physische Produkte, ohne
            zusätzliche
            Elemente hinzuzufügen oder anderweitig einen Mehrwert zu schaffen;
            <br><br>
            - die Darstellung von identifizierbaren Personen auf beleidigende, pornografische, obszöne, unmoralische,
            diffamierende, verleumderische oder politische Weise;
            <br><br>
            - oder die Suggestion, dass abgebildete Personen, Marken, Organisationen, etc. bestimmte Produkte oder
            Dienstleistungen befürworten oder billigen, es sei denn es wurde eine Genehmigung dazu erteilt.
            <br><br>
            Beachte bitte, dass alle Inhalte auf PhotoHub zwar für kommerzielle und nicht-kommerzielle Zwecke frei
            verwendbar
            sind, gezeigte Elemente in den Bildern, wie identifizierbare Personen, Logos und Marken, jedoch zusätzlichen
            Urheberrechten, Eigentumsrechten, Personenrechten, Markenrechten usw. unterliegen können. Die Zustimmung
            eines
            Dritten oder die Lizenz dieser Rechte können insbesondere für kommerzielle Anwendungen erforderlich sein.
            PhotoHub
            garantiert nicht, dass solche Zustimmungen oder Lizenzen eingeholt wurden, und lehnt ausdrücklich jegliche
            Haftung
            in dieser Hinsicht ab.
        </p>
    </section>
</article>
{% endblock content %}

photo_webs/web/templates/web/search.html
{% extends "web/home.html" %}
{% load static %}
{% load app_filters %}

{% block intro %}
<div class="card text-center mt-5 bg-dark" style="border-radius: 0;">
    <div class="card-body pt-5 pb-5" style="background-image: url({% static "media/default_page_banner.jpeg" %}); background-size: cover; 
    background-repeat: no-repeat;
    background-position: center center;">
        <br>
        <h1 class="text-light">{{pk|title}}</h1>
        {% if pk|get_search_description != none %}
        <h2 class="text-light">{{ pk|get_search_description|dict_key:'text' }}</h2>
        {% for btn in pk|get_search_description|dict_key:'suggestions'  %}
        <a href="{% url 'web:search' pk=btn|title %}" class="btn btn-primary">{{btn|title}}</a>
        {% endfor %}
        {% endif %}
        <h2><a></a></h2>
    </div>
    <div class="card-footer text-dark bg-primary">
        {% if user.is_authenticated %}
        Hello {{ user.username }}. Add new pictures to your <a href="{% url 'user:profile' %}{{ user.id }}"
            class="text-light">profile</a>.
        {% else %}
        Discover the latest pictures.
        {% endif %}
    </div>
</div>

{% endblock intro %}

{% block content %}
<div class="card bg-dark" style="width: 100%;">
    <div class="card-body">
        <h5 class="card-title text-light">Users</h5>
        <h6 class="card-subtitle mb-2 text-muted">Discover great profiles related to your search</h6>
    </div>
</div>

<div class="gallery-big mini-cards">
    {% for user in all_users %}
    {% if pk|is_user_in_search:user == True %}
    <div class="card bg-dark text-light">
        <div class="card-body">
        <a href="{% url 'user:profile' %}{{user.id}}" class="text-white">
            <img src="{{ user.profile.profile_img.url }}"
                class="rounded border border-primary float-left mr-3" style="width: 50px;"
                alt="Profile picture of {{ user.username }}.">
            {{user}}
            <br>{{user.profile.bio_short}}</a>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>

<div class="card bg-dark" style="width: 100%;">
    <div class="card-body">
        <h5 class="card-title text-light">Images</h5>
        <h6 class="card-subtitle mb-2 text-muted">We found these pictures for you</h6>
    </div>
</div>

<div class="gallery-big">
{% for image in all_imgposts %}
{% if pk|is_image_in_search:image == True %}

{% include 'imageposts/snippet/img_card.html' with image=image user=user %}

{% endif %}
{% endfor %}
</div>
{% endblock content %}

photo_webs/web/templates/web/terms.html
{% extends "web/base.html" %}

{% block intro %}
{% load static %}

<div class="card text-center mt-5 bg-dark" style="border-radius: 0;">
    <div class="card-body pt-5 pb-5" style="background-image: url({% static "media/default_page_banner.jpeg" %}); background-size: cover; 
    background-repeat: no-repeat;
    background-position: center center;">
        <br>
        <h1 class="text-light">Imprint and Terms of Service</h1>
    </div>
    <div class="card-footer text-dark bg-primary">
        {% if user.is_authenticated %}
        Hello {{ user.username }}. Add new pictures to your <a href="{% url 'user:profile' %}{{ user.id }}"
            class="text-light">profile</a>.
        {% else %}
        Discover the latest pictures.
        {% endif %}
    </div>
</div>

{% endblock intro %}

{% block content %}

<article class="p-4">
    <a href="{% url 'web:imprint_de' %}" class="text-light btn btn-primary">deutsch</a>
    <a name="imprint"></a>
    <h2 class="text-light mt-3">Imprint</h2>
    <p class="text-light">Marc Störmer, Cem Saygili, Matti Schwartz, Duygu Köse,Serdar Korkmaz & Muharrem Yavuz</p>
    <p class="text-light">Beuth University of Applied Sciences</p>
    <p class="text-light"><strong>Adresse:</strong> Luxemburger Str.10 , 13353 Berlin</p>
    <p class="text-light"><strong>Tel.: 030/4504021</strong></p>
    <a name="terms"></a><br>
    <h2 class="text-light mt-5"><strong>Terms of Service</strong></h2>
    <section class="card border-info bg-dark p-4 mt-4">
        <h2 class="text-light">Terms</h2>
        <p class="text-light">
            <strong>PhotoHub</strong>
            <br><br>
            PhotoHub is a freely usable photo platform. Your use of the service and our provision of the service to you, constitutes an agreement by you and PhotoHub to be bound by the terms and conditions in these terms of Service.
            <br>
            Please read these Terms of service carefully. By signing up for or otherwise using the service, you are telling us that you have read, understood and agreed to be bound by these terms of service.
            <br><br>
            PhotoHub and/or its third-party licensors retain ownership of all intellectual property rights on this Website, the services and any software, mobile applications, web browser extensions and/or bookmarklets made available to you in connection with the services. However, we do not claim any ownership on the Content you or our other users Post.
            <br><br>
            <strong>General Terms</strong>
            <br><br>
            The service is designed for people who are at least 13 years old. If you are 13 or older, you promise to us that your use of the service won't break any laws or regulations. You are responsible for your use of our services. For any content you post, you're using the services and for any consequences or liability arising there from. As part of the services, you will be provided the opportunity to contribute inspirational content to the PhotoHub community. You can upload content from your device to our service. Please note that other users of the services can view all content.
            <br><br>
            You are solely responsible for your interaction with other users of the services, whether online or offline. We reserve the right but have no obligation to monitor or become involved in disputes between you and other users.
            <br><br>
            <strong>User posts and Third Party Content</strong>
            <br><br>
            We do not review new content prior to it being posted on our Website or through the Services. By Posting Content to our server, you guarantee us that you have the right to make this content available for use in accordance herewith. You further agree that the content you post to the services will not contain third-party copyrighted material, or material that is subject to other third-party rights (including rights relating to publicity and privacy), unless you have permission from the rightful owner of the material or you are otherwise legally entitled to post the material and to grant PhotoHub all license rights.
            <br><br>
            We do not guarantee, support or represent the completeness, reliability, veracity or accuracy of any content that appears on our website or the services. You understand that by using the services, you may be exposed to content, that you find offensive, inaccurate, otherwise inappropriate, deceptive or in some cases mislabeled. We expressly disclaim any liability for content.
            <br><br>
            <strong>Uploading content</strong>
            <br><br>
            By uploading images or videos to the site, you grant PhotoHub an irrevocable, worldwide, non-exclusive and royalty-free right to use, download or copy the content for commercial and non-commercial purposes free of charge.
            <br><br>
            You are responsible for your uploaded pictures and videos and guarantee, that
            <br><br>
            a. you own all rights to the content you upload on the site and that the content does not infringe copyright, proprietary rights, trademark law or other applicable rights of third parties,
            <br><br>
            b. you own and/or pass on all rights to the image that are necessary for worldwide, free, irrevocable and indefinite use, where required by law. This includes in particular valid model contracts, photography permits, as well as other licenses and rights of third parties.
            <br><br>
            Although PhotoHub strictly ensures that uploaded images are not misused or contrary to the terms of use, we cannot guarantee this and will not be held responsible in the current case.
            <br><br>
        </p>
    </section>
</article>
{% endblock content %}