photo_webs/imageposts/urls.py
from django.urls import path

from . import views

app_name = "imageposts"

urlpatterns = [
    path("post/", views.add_post, name="add-post"),
    path("post/<int:pk>/", views.ImageDetailView.as_view(), name="show"),
    path("post/<int:pk>/edit/", views.edit_post, name="edit"),
]

photo_webs/photo_webs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', include('web.urls')),
    path("user/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls")),
    path("imageposts/", include("imageposts.urls")),
    path("", include("web.urls")),
    # path('', ImagepostListView.as_view(), name='all-imgposts'),
    # path('', include('images.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo_webs/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("", views.profile, name="profile"),
    path("settings/", views.user_edit, name="user-settings"),
    path("profile/settings/", views.profile_edit, name="profile-settings"),
    path("instagram/", views.add_insta_profile, name="profile-insta"),
    path("instagram/<int:pk>/", views.show_insta_profile, name="profile-insta-show"),
    path("settings/password/", views.change_password, name="change_password"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="profile"),
    path("<int:pk>/images/", views.UserImagesView.as_view(), name="profile-images"),
    path("<int:pk>/bio/", views.UserBioView.as_view(), name="profile-bio"),
    path("<int:pk>/followers/", views.FollowerView.as_view(), name="profile-follows"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

photo_webs/web/urls.py
from django.urls import path
from imageposts.views import ImagepostListView

from . import views

app_name = "web"

urlpatterns = [
    path("", ImagepostListView.as_view(), name="all-imgposts"),
    path("license/", views.license, name="license"),
    path("license/de/", views.license_de, name="license_de"),
    path("imprint/", views.imprint, name="imprint"),
    path("imprint/de/", views.imprint_de, name="imprint_de"),
    path("license/de", views.license_de, name="license_de"),
    path("search/<str:pk>", views.search, name="search"),
]

photo_webs/imageposts/models.py
from django.contrib.auth.models import User
from django.db import models

CATEGORY_CHOICES = (
    ("no category", "NO CATEGORY"),
    ("nature", "NATURE"),
    ("humans", "HUMANS"),
    ("animals", "ANIMALS"),
    ("buildings", "BUILDINGS"),
    ("abstract", "ABSTRACT"),
    ("wallpaper", "WALLPAPER"),
)


class Imagepost(models.Model):
    title = models.TextField(max_length=30)
    img = models.ImageField(upload_to="media", null=True, default="media/773433.jpg")
    img_thumbnail = models.ImageField(
        upload_to="media/thumbnails", null=True, default="media/773433.jpg"
    )
    description = models.TextField(max_length=100)
    long_description = models.TextField(max_length=1000)
    license_text = models.TextField(max_length=5000, blank=True, null=True)
    pinned = models.BooleanField(default=False)
    category = models.CharField(
        max_length=30, choices=CATEGORY_CHOICES, default="green"
    )
    tags = models.TextField(null=True, max_length=200)
    username = models.TextField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(auto_now=True)
    favs = models.IntegerField(default=0)

    def summary(self):
        return self.title + ": " + self.description

    def __str__(self):
        return self.title + " +" + str(self.favs)

photo_webs/imageposts/forms.py
from django import forms

from .models import Imagepost


class ImagepostForm(forms.ModelForm):
    class Meta:
        model = Imagepost
        fields = [
            "title",
            "img",
            "description",
            "long_description",
            "license_text",
            "pinned",
            "category",
            "tags",
        ]

        widgets = {
            "license_text": forms.Textarea(
                attrs={
                    "placeholder": "Enter nothing for PhotoHub license or select free to use. Text entered here is used as license text."
                }
            ),
        }

photo_webs/imageposts/views.py
import sys
from io import BytesIO

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView
from PIL import Image

from .forms import ImagepostForm
from .models import Imagepost


class ImageDetailView(DetailView):
    model = Imagepost
    context_object_name = "image"


class ImagepostListView(ListView):
    model = Imagepost
    context_object_name = "all_imgposts"
    paginate_by = 24
    template_name = "web/home.html"
    ordering = ["-timestamp"]


def image_resize_and_autorotate(imageFile, imageName):
    im = Image.open(imageFile)
    exif = im._getexif()

    if im.mode in ("RGBA", "P"):
        im = im.convert("RGB")

    im.thumbnail((4096, 4096), resample=Image.ANTIALIAS)

    # if image has exif data about orientation, let's rotate it
    orientation_key = 274  # cf ExifTags
    if exif and orientation_key in exif:
        orientation = exif[orientation_key]

        rotate_values = {3: Image.ROTATE_180, 6: Image.ROTATE_270, 8: Image.ROTATE_90}

        if orientation in rotate_values:
            im = im.transpose(rotate_values[orientation])

    im_io = BytesIO()
    im.save(im_io, format="JPEG")
    im_io.seek(0)

    im_file = InMemoryUploadedFile(
        im_io, None, imageName, "image/jpeg", sys.getsizeof(im_io), None
    )
    return im_file


def create_thumbnail(imageFile, imageName):
    im = Image.open(imageFile)

    # resize image
    max_size = (1600, 900)
    im.thumbnail(max_size, Image.ANTIALIAS)

    # crop image
    im_height = im.size[1]
    im_width = im.size[0]
    im_ratio = im_height / float(im_width)

    new_ratio = 16 / 9

    left = 0
    right = im_width
    top = 0
    bottom = im_height

    if not im_ratio == new_ratio:
        if im_height < im_width:
            new_width = (im_height / 9) * 16

            left = (im_width - new_width) / 2
            right = left + new_width
            top = 0
            bottom = im_height
        else:
            new_height = (im_width / 16) * 9

            left = 0
            right = im_width
            top = (im_height - new_height) / 2
            bottom = top + new_height

    cropped_im = im.crop((left, top, right, bottom))

    if cropped_im.mode in ("RGBA", "P"):
        cropped_im = cropped_im.convert("RGB")

    # save image to object
    im_io = BytesIO()
    cropped_im.save(im_io, format="JPEG")
    im_io.seek(0)

    # build and  InMemoryUploadedFile from im
    im_file = InMemoryUploadedFile(
        im_io, None, imageName, "image/jpeg", sys.getsizeof(im_io), None
    )
    return im_file


PHOTOHUB_LICENSE = """PhotoHub license - use of images
Images on PhotoHub are provided under the PhotoHub license under the following conditions.
The PhotoHub license gives you an irrevocable, worldwide, non-exclusive and royalty-free right to use, download, copy and modify the images for commercial and non-commercial purposes. It is not necessary to name the photo author or PhotoHub, but we would be happy to provide a voluntary source.

The PhotoHub license does not allow:

- the sale or distribution of images in digital and physical form, in particular as stock photos or digital wallpapers;

- the sale or distribution of images e.g. as posters, digital prints or physical products, without adding additional elements or otherwise creating added value;

- depicting identifiable people in an offensive, pornographic, obscene, immoral, defamatory or political manner;

- or the suggestion that depicted people, brands, organizations, etc. endorse certain products or services unless authorized to do so.

Please note that although all content on PhotoHub is freely usable for commercial and non-commercial purposes, elements shown in the images, such as identifiable people, logos and brands, may be subject to additional copyrights, property rights, personal rights, trademark rights, etc. Third party approval or licensing of these rights may be required, particularly for commercial applications. PhotoHub does not guarantee that such consent or licenses have been obtained and expressly disclaims any liability in this regard.
"""


def add_post(request):
    if request.method == "POST":
        form = ImagepostForm(request.POST, request.FILES)
        if form.is_valid():
            imagepost = form.save()
            imagepost.user = request.user

            if not form.cleaned_data["license_text"]:
                imagepost.license_text = PHOTOHUB_LICENSE

            imagepost.img = image_resize_and_autorotate(
                form.cleaned_data["img"], imagepost.img.name
            )
            imagepost.img_thumbnail = create_thumbnail(
                form.cleaned_data["img"], imagepost.img.name
            )

            imagepost.save()
            return redirect("/")
    else:
        form = ImagepostForm()
    return render(request, "imageposts/post.html", {"form": form})


def edit_post(request, pk):
    post = get_object_or_404(Imagepost, pk=pk)
    if request.method == "POST":
        form = ImagepostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect("/imageposts/post/{}/edit/".format(pk), pk=pk)
    else:
        if request.user != post.user:
            return redirect("/imageposts/post/{}/".format(pk), pk=pk)
        else:
            form = ImagepostForm(instance=post)
            return render(
                request, "imageposts/edit_imagepost.html", {"form": form, "pk": pk}
            )

photo_webs/imageposts/templates/imageposts/edit_imagepost.html
{% extends "web/base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="card m-5">
  <h5 class="card-header">Edit Imagepost</h5>
  <div class="card-body">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!--{{ form.as_p }}-->
      {% bootstrap_form form %}
      <p>
      <a href="/imageposts/post/{{pk}}">View on Website</a>
      </p>
      <button class="btn btn-primary" type="submit">Submit</button>
    </form>
  </div>
</div>
{% endblock content %}

photo_webs/imageposts/templates/imageposts/imagepost_detail.html
{% extends "web/base.html" %}
{% load app_filters %}

{% block content %}
<div class="card-body bg-light mt-4" style="padding: 1.25rem;">
    <div id="detail_card">
      <img class="card-img-top mt-4" src="{{ image.img.url }}" alt="Card image cap">
      <div class="card-body">
        <h3 class="card-title text-center">{{image.title}}</h3>
            <p class="card-text text-center">{{ image.long_description }}</p>
        <br>
        <a download="{{image.title}}", href="{{image.img.url}}" type="button" class="btn btn-outline-primary btn-block"><strong>Download Image - {{image.img.width}} x {{image.img.height}}</strong></a>
        {% if image.user == user %}
        <a href="{% url 'imageposts:edit' pk=image.id %}" type="button" class="btn btn-outline-danger btn-block"><strong>Edit Image</strong></a>
        {% endif %}
        <br>
          <ul class="list-group list-group-flush">
            <li class="list-group-item  bg-light text-center">
                <h5>Categorie </h5>{{ image.category }}
            </li>
            <li class="list-group-item  bg-light text-center">
                <h5>Tags </h5>{% for tag in image.tags|split_text:"," %}<a href="{% url 'web:search' pk=tag|title %}"
                    class="btn btn-primary m-2">{{tag|title}}</a>{% endfor %}
            </li>
            <li class="list-group-item  bg-light text-center">
                <a href="{% url 'user:profile' %}{{image.user.id}}" class="text-white text-left">
                    <div class="card bg-dark text-light">
                        <div class="card-body">
                            <img src="{{ image.user.profile.profile_img.url }}"
                                class="rounded border border-primary float-left mr-3" style="width: 50px;"
                                alt="Profile picture of {{ follower.username }}.">
                            {{image.user}}
                            <br>{{image.user.profile.bio_short}}
                        </div>
                    </div>
                </a>
            </li>
            <li class="list-group-item  bg-light">
                <h5 class="text-center mt-3"><strong>License</strong></h5>
                <br>{% for line in image.license_text|split_text %}<p>{{ line }}</p>{% endfor %}
            </li>
        </ul>
          <div class="card-body">
              </div>
    </div>
</div>
</div>

    {% endblock content %}

photo_webs/imageposts/templates/imageposts/post.html
{% extends "web/base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="card m-5">
    <h5 class="card-header">Upload image</h5>  

  <div class="card-body">
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">upload</button>
      </form>
    </div>
    </div>
    
{% endblock content %}
{% block button_upload %}{% endblock button_upload %}